alias ApxrIo.Repo

alias ApxrIo.{
  Accounts.AuditLog,
  Accounts.Auth,
  Accounts.Email,
  Accounts.Key,
  Accounts.KeyPermission,
  Accounts.Keys,
  Accounts.Organization,
  Accounts.Organizations,
  Accounts.OrganizationUser,
  Accounts.Session,
  Accounts.User,
  Accounts.Users,
  Emails,
  Emails.Mailer,
  Repository.Assets,
  Repository.Owners,
  Repository.Project,
  Repository.ProjectMetadata,
  Repository.ProjectOwner,
  Repository.Projects,
  Repository.RegistryBuilder,
  Repository.Release,
  Repository.ReleaseMetadata,
  Repository.ReleaseRetirement,
  Repository.Releases,
  Repository.Repository,
  Learn.Experiment,
  Learn.ExperimentMetadata,
  Learn.ExperimentTrace,
  Learn.ExperimentGraphData,
  Learn.Experiments,
  Learn.Runner,
  Serve.Artifact,
  Serve.ArtifactMetadata,
  Serve.ArtifactStats,
  Serve.Artifacts,
  Serve.Gateway
}

import_if_available(Ecto.Query, only: [from: 1, from: 2])
