---
# ansible 2.6
# - name: lock root account
#   become: 'yes'
#   become_method: sudo
#   user:
#     name: root
#     password_lock: 'yes'
#   tags:
#     - users
#     - lock_root
#     - security

- name: lock root account
  become: 'yes'
  become_method: sudo
  command: usermod -L root
  environment:
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  tags:
    - users
    - lock_root
    - security
    - skip_ansible_lint
...
