---
# Build system setup
# ansible-playbook -u $USER -v -l nginx-server playbooks/setup-nginx.yml -D

- name: Manage users
  hosts: '*'
  become: true
  roles:
    - users

- name: Install common
  hosts: '*'
  become: true
  gather_facts: true
  vars:
    tools_other_packages:
      - git
      - vim
      - tmux
      - htop
      - curl
      - sudo
  roles:
    - common-minimal
    - tools-other