---
# Build system setup
# ansible-playbook -u $USER -v -l build-server playbooks/setup-build.yml -D

- name: Manage users
  hosts: '*'
  become: true
  roles:
    - users

- name: Install common
  hosts: '*'
  become: true
  gather_facts: true
  vars:
    tools_other_packages:
      - git
      - vim
      - tmux
      - htop
      - curl
      - sudo
  roles:
    - common-minimal
    - tools-other
    - iptables

- name: Install asdf
  hosts: '*'
  become: true
  gather_facts: true
  vars:
    asdf_version: v0.6.3
    asdf_user: "{{ users_deploy_user }}"
    asdf_plugins:
      - name: erlang
      - name: elixir
  vars_files:
    - "../vars/build-{{ ansible_os_family }}.yml"
    - "../vars/build-{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
  roles:
    - tools-other
    - asdf
    - ocha.yarn

- name: Set up app
  hosts: '*'
  become: true
  become_user: "{{ users_deploy_user }}"
  tasks:
    - name: Set vars
      set_fact:
        build_base_dir: "{{ asdf_user_home }}/build"
        build_dir: "{{ asdf_user_home }}/build/{{ elixir_release_name }}"

    - name: Create build dir
      file: path="{{ build_base_dir }}" state=directory owner={{ users_deploy_user }} group={{ users_deploy_group }} mode=0755
