# Web system setup
#
# ansible-playbook -u $USER -v -l web-servers playbooks/setup-web.yml -D

- name: Manage users
  hosts: '*'
  become: true
  gather_facts: true
  vars:
    incl_systemd: true
  roles:
    - users

- name: Install common
  hosts: '*'
  become: true
  vars:
    tools_other_packages:
      - sudo
  roles:
    - common-minimal
    - tools-other
    - iptables
    - iptables-http

- name: Set up web app
  hosts: '*'
  become: true
  tasks:
    - name: Create deploy dirs
      file: path={{ item }} state=directory owner={{ elixir_release_deploy_user }} group={{ elixir_release_app_group }} mode=0750
      with_items:
        - "{{ elixir_release_deploy_dir }}"
        - "{{ elixir_release_releases_dir }}"