# These are the default vars that apply to all servers

# OS user account that deploys the app and owns the code files
users_deploy_user: deploy
# OS group for deploy
users_deploy_group: "{{ users_deploy_user }}"

# External name of the app, used to name directories
elixir_release_name: apxr-io

# OS user the app runs under
elixir_release_app_user: apxr-io
elixir_release_app_group: "{{ elixir_release_app_user }}"

# OS user for deploy
elixir_release_deploy_user: deploy
elixir_release_deploy_group: "{{ elixir_release_deploy_user }}"

# Base directory for deploy files
elixir_release_deploy_dir: "/srv/{{ elixir_release_name }}"
elixir_release_releases_dir: "{{ elixir_release_deploy_dir }}/releases"