# These are the default vars that apply to all servers

# OS user account that deploys the app and owns the code files
users_deploy_user: deploy
# OS group for deploy
users_deploy_group: "{{ users_deploy_user }}"
