%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.5.1

-ifndef(apxr_pb_signed).
-define(apxr_pb_signed, true).

-define(apxr_pb_signed_gpb_version, "4.5.1").

-ifndef('SIGNED_PB_H').
-define('SIGNED_PB_H', true).
-record('Signed',
        {payload                :: iodata(),        % = 1
         signature              :: iodata() | undefined % = 2
        }).
-endif.

-endif.
