%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.5.1

-ifndef(apxr_pb_versions).
-define(apxr_pb_versions, true).

-define(apxr_pb_versions_gpb_version, "4.5.1").

-ifndef('VERSIONS_PB_H').
-define('VERSIONS_PB_H', true).
-record('Versions',
        {projects = []          :: [apxr_pb_versions:'Project'()] | undefined, % = 1
         repository             :: iolist()         % = 2
        }).
-endif.

-ifndef('PROJECT_PB_H').
-define('PROJECT_PB_H', true).
-record('Project',
        {name                   :: iolist(),        % = 1
         versions = []          :: [iolist()] | undefined, % = 2
         retired = []           :: [integer()] | undefined % = 3, 32 bits
        }).
-endif.

-endif.
