%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.5.1

-ifndef(apxr_pb_project).
-define(apxr_pb_project, true).

-define(apxr_pb_project_gpb_version, "4.5.1").

-ifndef('PROJECT_PB_H').
-define('PROJECT_PB_H', true).
-record('Project',
        {releases = []          :: [apxr_pb_project:'Release'()] | undefined, % = 1
         name                   :: iolist(),        % = 2
         repository             :: iolist()         % = 3
        }).
-endif.

-ifndef('RELEASE_PB_H').
-define('RELEASE_PB_H', true).
-record('Release',
        {version                :: iolist(),        % = 1
         checksum               :: iodata(),        % = 2
         retired                :: apxr_pb_project:'RetirementStatus'() | undefined % = 3
        }).
-endif.

-ifndef('RETIREMENTSTATUS_PB_H').
-define('RETIREMENTSTATUS_PB_H', true).
-record('RetirementStatus',
        {reason                 :: 'RETIRED_OTHER' | 'RETIRED_INVALID' | 'RETIRED_SECURITY' | 'RETIRED_DEPRECATED' | 'RETIRED_RENAMED' | integer(), % = 1, enum RetirementReason
         message                :: iolist() | undefined % = 2
        }).
-endif.

-endif.
